### ISSUE TITLE
Difference between index.md, index.json, etc

### ISSUE THREAD

**Issue by fabiopagoti** [SAP/openui5-docs#11]
What is the difference between the files below?

- `0index.md`
- `index.md`
- `index.json`

I added a new page in my fork on those but I could only see the new page after adding it to `sidebar.md`

Could you please explain the purpose of each file? Specially inside the [CONTRIBUTING](https://github.com/SAP/openui5-docs/blob/master/CONTRIBUTING.md) page?

**Comment by OlMue** [comment]
Hi Fabio,
as you probably already guessed, these files deal with the hierarchy of the documentation pages [here](https://github.com/SAP/openui5-docs/blob/master/docs/index.md) and [here](https://sap.github.io/openui5-docs/#/README).

You don't really need to worry about these files or how to add your new page to the structure. GitHub is really only the collaboration platform for feedback and contributions. The real magic happens in our content management system. So any proposal you send is added to the CMS by our user assistance developers. It's enough if you let us know in a comment where you think your new page should be added.

I just added some FAQs to the [contributiong guidelines](https://github.com/SAP/openui5-docs/blob/master/CONTRIBUTING.md), but I think explaining the purpose of each index file is not necessary. I just added the general process for adding new pages, so I hope this question won't come up again for other users.

Best regards,
Oliver
