### ISSUE TITLE
Section 'Integration Testing with One Page Acceptance Tests (OPA5) -> Simulating User Interactions on Controls' contains not working code

### ISSUE THREAD

**Issue by flovogt** [SAP/openui5-docs#16]
Hi Team,

the page: https://openui5.hana.ondemand.com/#/topic/8615a0b9088645ae936dbb8bbce5d01d
contains the section `Choosing an Item from sap.m.Select` in this section there is the sentence `Here's an example showing how to choose an item from sap.m.Select or sap.m.ComboBox`. But with Combobox this approach does not work.

See following code to achieve the selecting of an item of a combobox:
/**
 * Selects the suggestion item of a sap.m.Combobox with the text <code>mParameters.value</code> on the control with the <code>mParameters.controlId</code>
 *
 * @param {object} mParameters The parameters
 * @param {string} mParameters.controlId The id of the control
 * @param {any} [mParameters.fragmentId] If the control is placed inside a fragment, the id of the fragment
 * @param {string} mParameters.viewName The viewName
 * @param {any} mParameters.value If also the value of the control should be checked, this is the expected value
 *
 * @returns {jQuery.promise} The promise to wait until it is resolved
 */
iSelectComboBoxItemWithText: function (mParameters) {
	return this.waitFor({
		id: mParameters.controlId,
		viewName: mParameters.viewName,
		fragmentId: mParameters.fragmentId,
		actions: new Press(),
		success: function (oControl) {
			return this.waitFor({
				controlType: "sap.m.StandardListItem",
				searchOpenDialogs: true,
				matchers: [new Ancestor(oControl), new Properties({
						title: mParameters.value
					})],
				actions: new Press(),
				success: function () {
					Opa5.assert.ok(true, "Selected the item with text: " + mParameters.value + " on the control with id: '" + mParameters.controlId + "'");
				},
				errorMessage: "The select item with text " + mParameters.value + " could not be pressed."
			});
		},
		errorMessage: "The combox item can not be selected."
	});
}

**Comment by OlMue** [comment]
@xtatica: Seems to be one of your topics.
@flovogt: Since you're an internal developer, you can use the SAP-internal GitHub for contributions. This is better for "internal" discussions, because other internal developers can be involved more easily. I'll send you an e-mail with the URL. Nevertheless, I'm going to keep this issue open this time.

**Comment by maximnaidenov** [comment]
@flovogt Thanks for mentioning this. Actually, the difference is the type of the list item and seems coleagues changed this recently. 
@xtatica 
Let's change the sentence: ..  from sap.m.Select or sap.m.ComboBox
to:
from sap.m.Select". For sap.m.Combobox you should use controlType: sap.m.StandardListItem.

**Comment by xtatica** [comment]
I updated it like that:

Here's an example showing how to choose an item from sap.m.Select, using the waitFor function of OPA5, and the Press action:
//codeblock example remains the same//
For sap.m.Combobox, use controlType: "sap.m.StandardListItem".

@maximnaidenov, is that ok?
