### ISSUE TITLE
Assigning function directly to "renderer" should no longer be encouraged

### ISSUE THREAD

**Issue by boghyon** [SAP/openui5-docs#33]
Specifying the renderer without `apiVersion: 2` (e.g. <code>renderer: <em>&lt;fn></em></code>) causes falling back to the legacy string-based rendering even with semantic rendering APIs, i.e. no DOM-patching can be performed.

And according to https://github.com/SAP/openui5/issues/2822, there won't be any implicit setting of the flag either.

Topics that mention <code>renderer: <em>&lt;fn></em></code> should be all updated; informing that <code>renderer: <em>&lt;fn></em></code> should no longer be used and that `apiVersion: 2` should be explicitly set. E.g.:

<div class="highlight highlight-source-js"><del><pre><span class="pl-en">renderer</span><span class="pl-k">:</span> <span class="pl-k">function</span>(oRM, oControl) {<span class="pl-c"><span class="pl-c">/*</span>...<span class="pl-c">*/</span></span>}</pre></del></div>

```js
renderer: {
  apiVersion: 2,
  render: function(oRM, oControl) {
    // ...
  }
}
```

**Comment by Thodd** [comment]
Hi @boghyon & @flovogt,

I'll close this issue with a reference on https://github.com/SAP/openui5-docs/issues/17.

Initially I thought I could just replace the usage of the "renderer" function, but that's to superficial.
The goal should be to have more general rework of the rendering topic. So I'll drop this bandaid for now
and have created an internal backlog item based on @boghyon initial proposal in issue 17.
That should also cover the removal of renderer function usage in favor of an in-place object syntax.

BR,
Thorsten
