### ISSUE TITLE
Step 27. of the Walkthrough: Update webapp/localService/metadata.xml file

### ISSUE THREAD

**Issue by gmkv** [SAP/openui5-docs#44]
Hello,
The `webapp/localService/metadata.xml` file doesn't describe the "status" property that is used througout that step.
Would you add it?

This has been reported on the OpenUI5 repo: https://github.com/SAP/openui5/issues/2992

Regards,
Georgi

**Comment by OlMue** [comment]
Hi Georgi,

I added it now, thanks!

Oliver
