### ISSUE TITLE
Dead API Links to ODataListBinding Methods

### ISSUE THREAD

**Issue by BenReim** [SAP/openui5-docs#47]
The documentation page [Accessing Data in Controller Code](https://ui5.sap.com/1.81.1/#/topic/17b30ac2d5474078be31e695e97450cc.html) links a to a couple of APIs pages that lead to a "_The requested resource was not found_." page.

Samples:

- https://ui5.sap.com/1.81.1/#/api/sap.ui.model.odata.v4.ODataListBinding.create
- https://ui5.sap.com/1.81.1/#/api/sap.ui.model.odata.v4.ODataListBinding.requestContexts
- https://ui5.sap.com/1.81.1/#/api/sap.ui.model.odata.v4.ODataModel.bindList

**Comment by KlattG** [comment]
Fixed from 1.82
