### ISSUE TITLE
Broken link to `sap.ui.mdc.sample.Field`

### ISSUE THREAD

**Issue by pubmikeb** [SAP/openui5-docs#61]
[Looking](https://openui5nightly.hana.ondemand.com/search/valueHelp) for samples of `valueHelp` property:

![13_201502](https://user-images.githubusercontent.com/17231333/137190005-f41f020a-0fa6-463d-9fcb-b52bcb65fea8.png)

I've got a result 
> _`sap.ui.mdc.sample.Field` (samples):MDC..._

with a link to https://openui5nightly.hana.ondemand.com/entity/sap.ui.mdc.sample.Field which is actually broken and returns:

> _The requested resource was not found._

OpenUI5: "1.96.0-SNAPSHOT (built at 2021/10/13 00:03h)"

**Comment by flovogt** [comment]
Hello @pubmikeb ,
Thank you for sharing this finding. I've created an internal incident 2280031605. The status of the issue will be updated here in GitHub.

**Comment by kineticjs** [comment]
The issue is fixed in 1.100.0
