### ISSUE TITLE
Documentation consistency: `sap/ui/VersionInfo` vs. `sap.ui.Device`

### ISSUE THREAD

**Issue by pubmikeb** [SAP/openui5-docs#63]
A consistency issue: for the namespace [`sap/ui/VersionInfo`](https://openui5nightly.hana.ondemand.com/api/module:sap/ui/VersionInfo) slashes are used to separate the packages, while for other components dots are used instead, e.g.: [`sap/ui/VersionInfo`](https://openui5nightly.hana.ondemand.com/api/module:sap/ui/VersionInfo) vs. [`sap.ui.Device`](https://openui5nightly.hana.ondemand.com/api/sap.ui.Device).

BTW, what's the difference between slashes and dots in the components' name?

**Comment by flovogt** [comment]
Already answered by https://github.com/SAP/openui5/issues/3383.
