### ISSUE TITLE
Missing Deprecation Info for sap.ui.layout.form.GridLayout

### ISSUE THREAD

**Issue by BenReim** [SAP/openui5-docs#65]
`GridLayout` is listed as layout option for the `SimpleFormLayout` without any note about its deprecation:
https://openui5.hana.ondemand.com/api/sap.ui.layout.form.SimpleFormLayout

**Comment by flovogt** [comment]
Hello @BenReim ,
Thank you for sharing this finding. I've created an internal incident 2280031556. The status of the issue will be updated here in GitHub.

**Comment by flovogt** [comment]
Fixed by https://github.com/SAP/openui5/commit/7520efb59fdd136fd4edaead370b701dbc611dc0
