### ISSUE TITLE
sap.m.Tokenizer Calculations based on desity mode incorrect

### ISSUE THREAD

**Issue by leotrinh** [SAP/openui5-docs#66]
Hi Support Team,
I've got issues: The first part of some F4 fields is cut/not displayed completely --> When F4 fields have only 1 token

![f4issue](https://user-images.githubusercontent.com/11898388/142963711-816ec5c5-bfec-4693-888b-4e53eedd2b19.png)

After multiple testing and deployment, it is determined that a certain change in the sapui5 library in version 1.94 is the cause of the issue, testing has been done and detected that the issue won’t happen if we use any sapui5 version between 1.90 and 1.93.

![2021-11-23_09h41_14](https://user-images.githubusercontent.com/11898388/142963797-0471ab3d-1fde-4fe1-8fa3-6d1f734c4dc9.png)

Please help me check this issue

**Comment by flovogt** [comment]
Hello @leotrinh ,
Thank you for sharing this finding. I've created an internal incident 2280031499. The status of the issue will be updated here in GitHub.

**Comment by MapTo0** [comment]
Hello @leotrinh 

Could you please provide a jsbin example with the issue so we can reproduce and debug it?

Regards,
Martin

**Comment by leotrinh** [comment]
hello @flovogt @MapTo0 
I see this issue resolved on the latest version.
Thanks for your support.
