### ISSUE TITLE
Contradicting guidelines about default aggregation in XML views/ fragments

### ISSUE THREAD

**Issue by boghyon** [SAP/openui5-docs#7]
In [_Keep Your Views Short and Simple_](https://github.com/SAP/openui5-docs/blob/977574ce1d1a731aab370c50c0b487bb8cc83669/docs/Keep_Your_Views_Short_and_Simple_b0d7db7.md), there is the suggestion to remove default aggregation tags:

> ### Remove Clutter From Your Views
>It's easy to save a few bytes and make your code a lot cleaner:
> + Don't define properties that are set to their default values.
> + Remove unused namespace aliases.
> + **Omit the content or items tag for controls that define default aggregations.**
> + Use self-closing XML tags for controls that don't define any aggregations.

On the other hand, the [_Walkthrough Step 11_](https://github.com/SAP/openui5-docs/blob/977574ce1d1a731aab370c50c0b487bb8cc83669/docs/Step_11_Pages_and_Panels_3b9d9f8.md) says the following:

> ### Conventions
> * Do not make implicit use of default aggregations but always declare the aggregation names explicitly in the view. In the example above, the `content` aggregation could also be omitted as the `Panel` control declares it as a default, but it makes the view harder to read.

Would be nice if this contradiction could be addressed internally.

I personally agree with the 1st guideline; omitting default aggregation tags not only reduces the file size, it actually improves readability by reducing levels of indentation. Additionally, the 2nd guideline defies the whole purpose of `defaultAggregation` in control metadata.

**Comment by OlMue** [comment]
Hi,
this is a good point, we will look into this.
Thanks and best regards,
Oliver

**Comment by OlMue** [comment]
Hi,
we removed the contradicting section from the Walkthrough step. You were right, this was outdated and is not a best practice.
Thanks again for bringing this to our attention!
Best regards,
Oliver
