### ISSUE TITLE
Rendering of page broken since 1.98.0

### ISSUE THREAD

**Issue by marianfoo** [SAP/openui5-docs#71]
Hi there,

the page `Variant for Bootstrapping from Content Delivery Network` is broken since 1.98.0.
Perhaps other pages are also affected, only here I noticed it.
https://openui5.hana.ondemand.com/1.98.0/#/topic/2d3eb2f322ea4a82983c1c62a33ec4ae
![image](https://user-images.githubusercontent.com/13335743/164166604-44c6f273-3fab-4f1a-a6a4-b4f30cf81baa.png)

Still works in 1.97.0:
https://openui5.hana.ondemand.com/1.97.0/#/topic/2d3eb2f322ea4a82983c1c62a33ec4ae
![image](https://user-images.githubusercontent.com/13335743/164166684-8e8a2bd0-52d1-4f69-9547-2820ca633de5.png)

**Comment by OlMue** [comment]
Hi Marian, thanks for brining this up. This has been fixed in 1.101: [https://openui5.hana.ondemand.com/1.101.0/#/topic/2d3eb2f322ea4a82983c1c62a33ec4ae](https://openui5.hana.ondemand.com/1.101.0/#/topic/2d3eb2f322ea4a82983c1c62a33ec4ae)
Thanks for your contribution! Best regards,
Oliver
