### ISSUE TITLE
Contradicting sentences about `core:require` in Fragments

### ISSUE THREAD

**Issue by boghyon** [SAP/openui5-docs#8]
In the end of the topic [_Require Modules in XML View and Fragment_](https://github.com/SAP/openui5-docs/blob/bb1ddbc5b005e4ea7992b31cf6e16478d28f777a/docs/Require_Modules_in_XML_View_and_Fragment_b11d853.md#corerequire-in-fragments), it says the following:

> `core:require` can be used in fragments and set on every element, **including `FragmentDefinition`.**

But then, it continues:

> When a view with a fragment is preprocessed, the `FragmentDefinition` node is **not** part of the resulting view and this is why `core:require` on `FragmentDefinition` does not work as expected. Therefore, `core:require` works on all elements in fragment other than the `FragmentDefinition` node when the view which contains the fragment is preprocessed.

I think the latter text is not valid anymore since it's possible to make use of `core:require` in the `FragmentDefinition` node: https://jsbin.com/luzekib/edit?js,output

**Comment by boghyon** [comment]
Now I get it.


## This works:
<sub>src: https://jsbin.com/luzekib/edit?js,output</sub>
```xml
<core:FragmentDefinition xmlns:core="sap.ui.core"
  core:require="{
    IntegerType: 'sap/ui/model/type/Integer'
  }">
  <!-- ... -->
</core:FragmentDefinition>
```
Whereas..

## This doesn't:
<sub>src: https://jsbin.com/baxetik/edit?js,output</sub>
```xml
<mvc:View xmlns:mvc="sap.ui.core.mvc">
  <core:FragmentDefinition xmlns:core="sap.ui.core"
    core:require="{
      IntegerType: 'sap/ui/model/type/Integer'
    }">
    <!-- ... -->
  </core:FragmentDefinition>
</mvc:View>
```

___

TBH, the mentioned paragraph is a bit confusing since it begins saying that `core:require` works on the `FragmentDefinition` node, and the next sentences deny it right away.

**Comment by SabineLoss** [comment]
In progress - waiting for feedback from dev

**Comment by stopcoder** [comment]
Hi @boghyon,

with the last paragraph in [Require Modules in XML View and Fragment](https://github.com/SAP/openui5-docs/blob/bb1ddbc5b005e4ea7992b31cf6e16478d28f777a/docs/Require_Modules_in_XML_View_and_Fragment_b11d853.md#corerequire-in-fragments), we want to point out that the `core:require` on `FragmentDefinition` doesn't work when the view where the fragment is used is **preprocessed**. The `preprocess` here means that either `preprocessor` is registered to `XMLView` or the `preprocessors` option is set when creating a `XMLView` instance, details can be seen [here](https://github.com/SAP/openui5-docs/blob/bb1ddbc5b005e4ea7992b31cf6e16478d28f777a/docs/Preprocessing_XML_Views_48b81b9.md#using-the-preprocessor). The `Fragment` is not defined inline in the `XMLView` but in a separate location.

What you found here is another case where the `core:require` doesn't take any effect when writing the `FragmentDefinition` inline within a `View` definition. This isn't mentioned in the documentation and should be added there.

In both of the cases where the `core:require` doesn't have any effect, the `FragmentDefinition` node isn't included in the created `XMLView` instance. Therefore the `core:require` attribute in the `FragmentDefinition` isn't available for its child nodes.

I will rewrite the paragraph regarding `core:require` in `Fragment` and explicitly state that the `core:require` doesn't work on `FragmentDefinition` node when:
 * The View where a fragment is used is preprocessed
 * A fragment is defined inline in a View

Best regards,
Jiawei
