### ISSUE TITLE
Step 27: Unit Test with QUnit

### ISSUE THREAD

**Issue by mattmcneilgit** [SAP/openui5-docs#85]
Walkthrough step 27 producing error:
Message:  Diff suppressed as the expected and actual results have an equivalent serialization
TypeError: this.getOwnerComponent is not a function

Click link "You can view and download all files" which is served by openui5.org: https://sdk.openui5.org/entity/sap.m.tutorial.walkthrough/sample/sap.m.tutorial.walkthrough.27
the same error is observed.

**Comment by flovogt** [comment]
Hi @mattmcneilgit, thanks a lot for opening this issue here. The "Walkthrough Tutorial" will be updated in one of the next UI5 releases and we will have also tackle this issue here.

**Comment by flovogt** [comment]
Fixed with https://github.com/SAP/openui5/commit/ad6a5b7536355a5bfadcdb4caed470b9c0570a76 and available with UI5 version 1.119.0. Please check https://sdk.openui5.org/1.119.0/#/entity/sap.m.tutorial.walkthrough/sample/sap.m.tutorial.walkthrough.27.
