### ISSUE TITLE
Not clear how to properly add new pages in the documentation

### ISSUE THREAD

**Issue by fabiopagoti** [SAP/openui5-docs#9]
After forking and serving the documentation using a http-server npm package and inspecting the files in the `docs` folder, I am having a hard to to understand the right way to add new pages in the documentation.

The files have some strange suffixes - First I thought it was a commit ID but I don't think so.

Also, each page has a "loio" which is also not clear.

What convention should I use when creating a new page?

**Comment by OlMue** [comment]
Hi Fabio,

you're right, we will add this information to the contribution guidelines.
Basically, you just add a simple markdown file (*.md) with your suggestion to the `docs` folder in your branch/fork, and then you create a pull request. We will then look at your contribution and discuss this.

You don't have to worry about the suffixes in the file names or the LOIO information in the MD files. These are IDs that help us locate the documentation topic in our internal content management system. But I will also add this to the contribution guidelines.

Thanks and best regards
Oliver

**Comment by OlMue** [comment]
I just added an FAQ about this to our [contributing guidelines](https://github.com/SAP/openui5-docs/blob/master/CONTRIBUTING.md).
